# Generated by Django 3.2.5 on 2022-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profiles/'),
        ),
    ]
